### ISSUE TITLE
fix CI/CD

### ISSUE THREAD

**Issue by illyrius666** [Structura-Engineering/AutoFrameCAD#191]
The CI/CD is not complete and functioning.

**TASK:**
- [ ] analyze current status
- [ ] (optional) add/remove features
- [ ] complete the pipeline
